name: build, test, deploy application

on:
  push:
    branches:
      - main
      - application

jobs:
  docker-build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: build docker image
        id: validate
        run: build.sh
